CREATE OR REPLACE PROCEDURE MVFIN.PROCEDURE_CONSULTA_TOTAL_MOVIMENTACAO (VALOR OUT VARCHAR2)
IS
P_VALOR NUMERIC;
BEGIN
   SELECT SUM(TM.VALOR)
     INTO P_VALOR
     FROM TB_MOVIMENTACAO TM;
   VALOR := P_VALOR;
END PROCEDURE_CONSULTA_TOTAL_MOVIMENTACAO;